/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 7heXiMiK
 */
public class Authorization extends javax.swing.JFrame {

    /**
     * @return the CountForm
     */
    public int getCountForm() {
        return CountForm;
    }

    /**
     * @param CountForm the CountForm to set
     */
    public void setCountForm(int CountForm) {
        this.CountForm = CountForm;
    }

    /**
     * @return the NameRpt
     */
    public static String getNameRpt() {
        return NameRpt;
    }

    /**
     * @param aNameRpt the NameRpt to set
     */
    public static void setNameRpt(String aNameRpt) {
        NameRpt = aNameRpt;
    }

    public static Connection conn = null;
    private int CountForm = 0;
    int statBtnNext = 0; //Яку дію виконує кнопка 

    private static String NameRpt = "";
    ResultSet X = null;

    @Override
    public void setName(String name) {
        super.setName(name); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Authorization
     */
    public Authorization() {
        initComponents();
        ;
        try {
            start();
        } catch (IOException ex) {
            Logger.getLogger(Authorization.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lblLogin1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        pnlBody = new javax.swing.JPanel();
        txtPass = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblPass = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pnlHead = new javax.swing.JPanel();
        btnSet = new javax.swing.JLabel();
        btnHide = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlActiv = new javax.swing.JPanel();
        lblActiv = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblPib = new javax.swing.JLabel();
        txtPib = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        btnUpdateCon = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        jButton3.setBackground(new java.awt.Color(126, 87, 195));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Увійти");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblLogin1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLogin1.setText("Логін");

        jSeparator3.setBackground(new java.awt.Color(255, 0, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 0, 204));
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 51, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlBody.setBackground(new java.awt.Color(66, 33, 148));
        pnlBody.setForeground(new java.awt.Color(255, 102, 255));
        pnlBody.setPreferredSize(new java.awt.Dimension(360, 535));
        pnlBody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBodyMouseEntered(evt);
            }
        });

        txtPass.setBackground(new java.awt.Color(66, 33, 148));
        txtPass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(null);
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassKeyTyped(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(169, 76, 175));
        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/right-arrow.png"))); // NOI18N
        btnLogin.setText("Увійти");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblPass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Пароль");

        lblLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Логін");

        txtLogin.setBackground(new java.awt.Color(66, 33, 148));
        txtLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setBorder(null);
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLoginKeyTyped(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 0, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 204));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        pnlHead.setBackground(new java.awt.Color(169, 76, 175));
        pnlHead.setPreferredSize(new java.awt.Dimension(116, 39));

        btnSet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/settings.png"))); // NOI18N
        btnSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetMouseClicked(evt);
            }
        });

        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/negative.png"))); // NOI18N
        btnHide.setContentAreaFilled(false);
        btnHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHideMouseClicked(evt);
            }
        });
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/close.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Авторизація");

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSet, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHide, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSeparator2.setBackground(new java.awt.Color(255, 0, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 0, 204));
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        javax.swing.GroupLayout pnlActivLayout = new javax.swing.GroupLayout(pnlActiv);
        pnlActiv.setLayout(pnlActivLayout);
        pnlActivLayout.setHorizontalGroup(
            pnlActivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnlActivLayout.setVerticalGroup(
            pnlActivLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        lblActiv.setBackground(new java.awt.Color(0, 0, 0));
        lblActiv.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblActiv.setForeground(new java.awt.Color(255, 255, 255));
        lblActiv.setText("Стан підключення");

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/login (1).png"))); // NOI18N

        lblRegister.setBackground(new java.awt.Color(0, 0, 0));
        lblRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setText("Не маєте аккаунту? Клікайте сюди для реєстрації");
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
        });

        lblPib.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPib.setForeground(new java.awt.Color(255, 255, 255));
        lblPib.setText("ПІБ");

        txtPib.setBackground(new java.awt.Color(66, 33, 148));
        txtPib.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPib.setForeground(new java.awt.Color(255, 255, 255));
        txtPib.setBorder(null);
        txtPib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPibActionPerformed(evt);
            }
        });
        txtPib.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPibKeyTyped(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(255, 0, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 0, 204));
        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N

        btnBack.setBackground(new java.awt.Color(169, 76, 175));
        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/back-arrow.png"))); // NOI18N
        btnBack.setText("Назад");
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdateCon.setBackground(new java.awt.Color(169, 76, 175));
        btnUpdateCon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnUpdateCon.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/arrows.png"))); // NOI18N
        btnUpdateCon.setText("Повторити");
        btnUpdateCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateConActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
            .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateCon, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(lblActiv)
                        .addGap(18, 18, 18)
                        .addComponent(pnlActiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(lblPib)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPib, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addComponent(lblLogin)
                                .addGap(29, 29, 29)
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBodyLayout.createSequentialGroup()
                                .addComponent(lblPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34))
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPib)
                    .addComponent(txtPib, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateCon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblActiv, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlActiv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetMouseClicked
        if (getCountForm() == 0) {
            Open con = new Open();
            try {
                con.Read();
            } catch (IOException ex) {
                Logger.getLogger(Authorization.class.getName()).log(Level.SEVERE, null, ex);
            }
            con.setVisible(true);
            setCountForm(1);
        }
    }//GEN-LAST:event_btnSetMouseClicked

    private void start() throws IOException {
        this.setLocationRelativeTo(null);//center screen
        txtPib.setHorizontalAlignment(txtPib.CENTER);
        txtLogin.setHorizontalAlignment(txtLogin.CENTER);
        txtPass.setHorizontalAlignment(txtPass.CENTER);
        MoveMouseListener mml = new MoveMouseListener(pnlHead, this);
        pnlHead.addMouseListener(mml);
        pnlHead.addMouseMotionListener(mml);
        lblPib.setVisible(false);
        txtPib.setVisible(false);
        jSeparator4.setVisible(false);
        btnUpdateCon.setVisible(false);
        btnBack.setVisible(false);
        File f = new File("UserSettings.txt");
        if (f.exists() && !f.isDirectory()) {

        } else {
            FileWriter nFile = new FileWriter("UserSettings.txt");
            nFile.write("127.0.0.1" + "\n");
            nFile.write("3306" + "\n");
            nFile.write("root" + "\n");
            nFile.write("" + "\n");
            nFile.write("MusicGen" + "\n");
            nFile.close();
        }
    }


    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        DB db = new DB();
        if (statBtnNext == 0) //Увійти
        {
            if (txtLogin.getText().length() > 0 && txtPass.getText().length() > 0) {

                X = db.GetUser("users", txtLogin.getText(), txtPass.getText());
                try {

                    if (X.next() == true) {
                        JOptionPane.showMessageDialog(rootPane, "Успішно", "Вхід", 1);
                        frmMain.setNameUser(txtLogin.getText());
                        frmMain m = new frmMain();
                        frmMain.setNameUser(txtLogin.getText());
                        m.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Неправильний логін або пароль", "Помилка данних", 2);
                    }
                    db.finalize();
                } catch (SQLException ex) {
                    Logger.getLogger(Authorization.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Заповніть всі поля", "Помилка данних", 2);
            }
        } else if (statBtnNext == 1) //Зареєструватись
        {
            if (txtLogin.getText().length() > 0 && txtPass.getText().length() > 0 && txtPib.getText().length() > 0) {
                db.GetR("users", txtLogin.getText());
                if (getNameRpt() == "") {
                    db.Register("users", txtPib.getText(), txtLogin.getText(), txtPass.getText());
                    JOptionPane.showMessageDialog(rootPane, "Успішно", "Реєстрація", 1);
                    lblTitle.setText("Авторизація");
                    btnBack.setVisible(false);
                    btnLogin.setText("Авторизуватись");
                    lblRegister.setVisible(false);
                    lblPib.setVisible(false);
                    txtPib.setVisible(false);
                    jSeparator4.setVisible(false);
                    txtLogin.setText("");
                    txtPass.setText("");
                    lblRegister.setVisible(true);
                    statBtnNext = 0;
                    db.finalize();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Користувач існує", "Дублювання даних", 2);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Заповніть всі поля", "Помилка данних", 2);
            }
        }

    }//GEN-LAST:event_btnLoginActionPerformed


    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed


    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnHideActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pnlBodyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBodyMouseEntered

    }//GEN-LAST:event_pnlBodyMouseEntered

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

    }//GEN-LAST:event_formMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        PlugIn();
    }//GEN-LAST:event_formWindowOpened

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered

    }//GEN-LAST:event_btnExitMouseEntered

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        lblTitle.setText("Реєстрація");
        lblRegister.setVisible(false);
        lblPib.setVisible(true);
        txtPib.setVisible(true);
        jSeparator4.setVisible(true);
        btnLogin.setText("Зареєструватись");
        btnBack.setVisible(true);
        txtLogin.setText("");
        txtPass.setText("");
        statBtnNext = 1;
    }//GEN-LAST:event_lblRegisterMouseClicked

    private void txtPibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPibActionPerformed

    private void btnUpdateConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateConActionPerformed
        PlugIn();
    }//GEN-LAST:event_btnUpdateConActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        lblTitle.setText("Авторизація");
        btnBack.setVisible(false);
        btnLogin.setText("Авторизуватись");
        lblRegister.setVisible(false);
        lblPib.setVisible(false);
        txtPib.setVisible(false);
        jSeparator4.setVisible(false);
        txtLogin.setText("");
        txtPass.setText("");
        lblRegister.setVisible(true);
        statBtnNext = 0;
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHideMouseClicked

    private void txtPibKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPibKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isLetterOrDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_SPACE)
                || (c == KeyEvent.VK_MINUS))) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtPibKeyTyped

    private void txtLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isLetterOrDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_SPACE)
                || (c == KeyEvent.VK_MINUS))) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtLoginKeyTyped

    private void txtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isLetterOrDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_SPACE)
                || (c == KeyEvent.VK_MINUS))) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtPassKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authorization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authorization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authorization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authorization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authorization().setVisible(true);
            }
        });
    }

    static void PlugIn() {
        DB a = new DB();
        conn = null;
        if (conn == null) {
            conn = a.Connect();
            if (conn == null) {
                pnlActiv.setBackground(Color.red);
                btnUpdateCon.setVisible(true);
                btnLogin.setEnabled(false);
                return;
            } else {
                pnlActiv.setBackground(Color.GREEN);
                btnUpdateCon.setVisible(false);
                btnLogin.setEnabled(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHide;
    public static javax.swing.JButton btnLogin;
    private javax.swing.JLabel btnSet;
    public static javax.swing.JButton btnUpdateCon;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblActiv;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPib;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblTitle;
    public static javax.swing.JPanel pnlActiv;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPib;
    // End of variables declaration//GEN-END:variables
}
