/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ximik
 */
public class FormAddDay extends javax.swing.JFrame {

    /**
     * @return the countP
     */
    public static int getCountP() {
        return countP;
    }

    /**
     * @param aCountP the countP to set
     */
    public static void setCountP(int aCountP) {
        countP = aCountP;
    }

    /**
     * @return the id
     */
    public static String getId() {
        return id;
    }

    /**
     * @param aId the id to set
     */
    public static void setId(String aId) {
        id = aId;
    }

    /**
     * @return the Date
     */
    public static String getDate() {
        return Date;
    }

    /**
     * @param aDate the Date to set
     */
    public static void setDate(String aDate) {
        Date = aDate;
    }

    /**
     * @return the Result
     */
    public static String getResult() {
        return Result;
    }

    /**
     * @param aResult the Result to set
     */
    public static void setResult(String aResult) {
        Result = aResult;
    }

    /**
     * @return the variantStart
     */
    public static int getVariantStart() {
        return variantStart;
    }

    /**
     * @param aVariantStart the variantStart to set
     */
    public static void setVariantStart(int aVariantStart) {
        variantStart = aVariantStart;
    }

    ResultSet X = null;
    DataBase a = null;
    static int countPerson = 0;
    public static ArrayList<String> listPerson = new ArrayList<>();
    public static ArrayList<String> listEdit = new ArrayList<>();
    private static int variantStart = 0;
    private static String Date = "";
    private static String Result = "";
    private static String id = "";
    private static int countP = 0;

    /**
     * Creates new form addDay
     */
    public FormAddDay() {
        initComponents();
        //this.setAlwaysOnTop(true);
        a = new DataBase();
        MoveMouseListener mml = new MoveMouseListener(pnlHead, this);
        pnlHead.addMouseListener(mml);
        pnlHead.addMouseMotionListener(mml);
        this.setLocationRelativeTo(null);
        getEmp();
        if (variantStart == 1) {

            SimpleDateFormat Fr = new SimpleDateFormat("y-MM-d", Locale.ENGLISH);
            try {
                MyDate.setDate(Fr.parse(Date));
                allW.setText(Result);
            } catch (ParseException ex) {
                Logger.getLogger(FormAddDay.class.getName()).log(Level.SEVERE, null, ex);
            }

            Component[] comp = pnlEm.getComponents();
            for (int i = 0; i < comp.length; i++) {
                String text = comp[i].toString();
                for (int j = 0; j < listEdit.size(); j++) {
                    if (text.indexOf(listEdit.get(j)) != -1) {
                        listPerson.add(listEdit.get(j) + "\n");
                        pnlEm.getComponent(i).setBackground(new Color(120, 101, 84));
                    }
                }
            }
            countPerson = countP;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlEm = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblExit1 = new javax.swing.JLabel();
        MyDate = new com.toedter.calendar.JDateChooser();
        allW = new javax.swing.JTextField();
        TitleCalendar = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        TitleCalendar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 219, 189));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlEm.setBackground(new java.awt.Color(255, 255, 255));
        pnlEm.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(pnlEm);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 300, 320));

        pnlHead.setBackground(new java.awt.Color(70, 43, 25));
        pnlHead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeadMousePressed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Додавання робочого дня");

        lblExit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit-2.png"))); // NOI18N
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(lblExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblExit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnlHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 40));

        MyDate.setDateFormatString("y-M-d");
        jPanel1.add(MyDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 320, 30));

        allW.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        allW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                allWKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                allWKeyTyped(evt);
            }
        });
        jPanel1.add(allW, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 80, -1));

        TitleCalendar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TitleCalendar.setForeground(new java.awt.Color(70, 43, 25));
        TitleCalendar.setText("Дата ");
        jPanel1.add(TitleCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnSave.setBackground(new java.awt.Color(120, 101, 84));
        btnSave.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/file-5.png"))); // NOI18N
        btnSave.setText("Зберегти");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 160, 40));

        TitleCalendar1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TitleCalendar1.setForeground(new java.awt.Color(70, 43, 25));
        TitleCalendar1.setText("Кількість кілограм:");
        TitleCalendar1.setToolTipText("");
        jPanel1.add(TitleCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //getEmp();
    }//GEN-LAST:event_formWindowOpened

    void getEmp() {
        a.GetInfoBox("PIB", "employees", "1");
        pnlEm.removeAll();
        for (int i = 0; i < a.list.size(); i++) {
            pnlEm.add(CreateBtn(a.array[i], 0));
        }
        pnlEm.updateUI();
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (listPerson.size() > 0 && allW.getText().length() > 0 && countPerson > 0 && MyDate.getDate() != null) {
            String result = listPerson.stream()
                    .map(n -> String.valueOf(n))
                    .collect(Collectors.joining());
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            double allWe = Double.parseDouble(allW.getText());
            double one = allWe / countPerson;
            BigDecimal bd = new BigDecimal(Double.toString(one));
            bd = bd.setScale(3, RoundingMode.HALF_UP);
            if (variantStart == 0) {
                a.MyInsert("allWork", dateFormat.format(MyDate.getDate()), countPerson, result, bd.doubleValue(), allWe);
                JOptionPane.showMessageDialog(this, "Успішно", "Додавання", 1);
                FormMain.GetData("allWork");
            } else if (variantStart == 1) {
                a.Update("allWork", dateFormat.format(MyDate.getDate()), countPerson, result, bd.doubleValue(), allWe, id);
                JOptionPane.showMessageDialog(this, "Успішно", "Редагування", 1);
                FormMain.GetData("allWork");
            }
            countPerson = 0;
            listEdit.clear();
            listPerson.clear();
            variantStart = 0;
            FormMain.setAddP(0);
            a.finalize();
            dispose();
        } else if (MyDate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Дату не вибрано", "Помилка", 2);
        } else if (listPerson.size() <= 0 || countPerson == 0) {
            JOptionPane.showMessageDialog(this, "Не вибрано робочих", "Помилка", 2);
        } else if (allW.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Не вказано кількість кілограм", "Помилка", 2);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void pnlHeadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlHeadMousePressed

    private void allWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_allWKeyTyped
        
    }//GEN-LAST:event_allWKeyTyped

    private void allWKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_allWKeyPressed

    }//GEN-LAST:event_allWKeyPressed

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        listEdit.clear();
        countPerson = 0;
        listPerson.clear();
        variantStart = 0;
        FormMain.setAddP(0);
        a.finalize();
        dispose();
    }//GEN-LAST:event_lblExit1MouseClicked
/**
 * Створення кнопки
 * @param name Ім'я
 * @param variant Варіант кліку
 * @return 
 */
    JButton CreateBtn(String name, int variant) {
        JButton b = new JButton(name);
        b.setPreferredSize(new Dimension(200, 50));
        b.setBackground(Color.WHITE);
        Font BigFontTR = new Font("TimesRoman", Font.BOLD, 14);
        b.setFont(BigFontTR);
        b.setVisible(true);
        b.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {

                if (e.getButton() == MouseEvent.BUTTON3) {
                    b.setBackground(Color.WHITE);
                    if (listPerson.indexOf(b.getText() + "\n") != -1) {
                        listPerson.remove(listPerson.indexOf(b.getText() + "\n"));
                        countPerson -= 1;
                    }

                } else if (e.getButton() == MouseEvent.BUTTON1) {
                    b.setBackground(new Color(120, 101, 84));
                    if (listPerson.indexOf(b.getText() + "\n") == -1) {
                        countPerson += 1;
                        listPerson.add(b.getText() + "\n");
                    }
                }
            }
        });

        return b;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddDay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser MyDate;
    private javax.swing.JLabel TitleCalendar;
    private javax.swing.JLabel TitleCalendar1;
    private javax.swing.JTextField allW;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlEm;
    private javax.swing.JPanel pnlHead;
    // End of variables declaration//GEN-END:variables
}
