/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.event.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ximik
 */
public class FormSettingsCalculation extends javax.swing.JFrame {

    /**
     * Creates new form FormCalculationSettings
     */
    
    static ResultSet X = null;
    public FormSettingsCalculation() {
        initComponents();
        MoveMouseListener mml = new MoveMouseListener(pnlHead, this);
        pnlHead.addMouseListener(mml);
        pnlHead.addMouseMotionListener(mml);
        this.setLocationRelativeTo(null);
        getParam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtValueKH = new javax.swing.JTextField();
        pnlHead = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTake = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPayRate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSt1Pay = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSt2Pay = new javax.swing.JTextField();
        btnSave2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtPayDef = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(240, 219, 189));

        txtValueKH.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtValueKH.setToolTipText("");
        txtValueKH.setCaretColor(new java.awt.Color(69, 73, 74));
        txtValueKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtValueKHMouseClicked(evt);
            }
        });
        txtValueKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValueKHKeyTyped(evt);
            }
        });

        pnlHead.setBackground(new java.awt.Color(70, 43, 25));
        pnlHead.setPreferredSize(new java.awt.Dimension(334, 46));

        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit-2.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Налаштування розрахунків");

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 43, 25));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Заробітна плата робочого");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 43, 25));
        jLabel2.setText("Гривень за один кілограм");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 43, 25));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Заробітна плата касира");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 43, 25));
        jLabel4.setText("Якщо виручка більше ");

        txtTake.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtTake.setToolTipText("");
        txtTake.setCaretColor(new java.awt.Color(69, 73, 74));
        txtTake.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTakeKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 43, 25));
        jLabel5.setText("гривень");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 43, 25));
        jLabel6.setText("заробітна плата = ");

        txtRate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtRate.setToolTipText("");
        txtRate.setCaretColor(new java.awt.Color(69, 73, 74));
        txtRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateActionPerformed(evt);
            }
        });
        txtRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRateKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 43, 25));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("+ ");

        txtPayRate.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtPayRate.setToolTipText("");
        txtPayRate.setCaretColor(new java.awt.Color(69, 73, 74));
        txtPayRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPayRateKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(70, 43, 25));
        jLabel9.setText("% від виручки");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(70, 43, 25));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Заробітна плата стажерів");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(70, 43, 25));
        jLabel11.setText("Стажер_1");

        txtSt1Pay.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtSt1Pay.setToolTipText("");
        txtSt1Pay.setCaretColor(new java.awt.Color(69, 73, 74));
        txtSt1Pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSt1PayKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(70, 43, 25));
        jLabel12.setText("Стажер_2");

        txtSt2Pay.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtSt2Pay.setToolTipText("");
        txtSt2Pay.setCaretColor(new java.awt.Color(69, 73, 74));
        txtSt2Pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSt2PayKeyTyped(evt);
            }
        });

        btnSave2.setBackground(new java.awt.Color(120, 101, 84));
        btnSave2.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        btnSave2.setForeground(new java.awt.Color(255, 255, 255));
        btnSave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/floppy-disk.png"))); // NOI18N
        btnSave2.setText("Зберегти");
        btnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(70, 43, 25));
        jLabel13.setText("в іншому випадку =");

        txtPayDef.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtPayDef.setToolTipText("");
        txtPayDef.setCaretColor(new java.awt.Color(69, 73, 74));
        txtPayDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayDefActionPerformed(evt);
            }
        });
        txtPayDef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPayDefKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(70, 43, 25));
        jLabel14.setText("гривень");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(70, 43, 25));
        jLabel15.setText("гривень");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(70, 43, 25));
        jLabel16.setText("гривень");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(70, 43, 25));
        jLabel17.setText("гривень");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTake, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave2)
                                .addGap(142, 142, 142))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPayRate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtValueKH, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPayDef, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSt1Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSt2Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValueKH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTake, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPayRate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPayDef, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSt1Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtSt2Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Отримання параметру ціни
     */
    void getParam()
    {
        DataBase DB = new DataBase();
        X = DB.GetParam("SELECT name, value FROM setcalc");
        
        try {
            while (X.next()) {
                if(X.getString(1).equals("За кілограм"))
                {
                    txtValueKH.setText(X.getString(2));
                }
                else if(X.getString(1).equals("ВиручкаВідсоток"))
                {
                    txtTake.setText(X.getString(2));
                }
                else if(X.getString(1).equals("Відсоток"))
                {
                    txtRate.setText(X.getString(2));
                }
                else if(X.getString(1).equals("ЗарплатаВідсоток"))
                {
                    txtPayRate.setText(X.getString(2));
                }
                else if(X.getString(1).equals("ЗвичайнаЗарплата"))
                {
                    txtPayDef.setText(X.getString(2));
                }
                else if(X.getString(1).equals("Стажер_1"))
                {
                    txtSt1Pay.setText(X.getString(2));
                }
                else if(X.getString(1).equals("Стажер_2"))
                {
                    txtSt2Pay.setText(X.getString(2));
                }
            }
            DB.finalize();
        } catch (SQLException ex) {
            Logger.getLogger(FormSettingsCalculation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave2ActionPerformed
        if(txtPayRate.getText().length()>0 && txtRate.getText().length()>0 && txtSt1Pay.getText().length()>0 && txtPayDef.getText().length()>0
                && txtSt2Pay.getText().length()>0 && txtTake.getText().length()>0 && txtValueKH.getText().length()>0)
        {
            try
            {
            double ValueKh = Double.parseDouble(txtValueKH.getText());
            double take = Double.parseDouble(txtTake.getText());
            double Rate = Double.parseDouble(txtRate.getText());
            double PayRate = Double.parseDouble(txtPayRate.getText());
            double PayDef = Double.parseDouble(txtPayDef.getText());
            double st1 = Double.parseDouble(txtSt1Pay.getText());
            double st2 = Double.parseDouble(txtSt2Pay.getText());
            DataBase DB = new DataBase();
            DB.MyUpdateCalc("setcalc", "За кілограм", ValueKh + "");
            DB.MyUpdateCalc("setcalc", "ВиручкаВідсоток", take + "");
            DB.MyUpdateCalc("setcalc", "Відсоток", Rate + "");
            DB.MyUpdateCalc("setcalc", "ЗарплатаВідсоток", PayRate + "");
            DB.MyUpdateCalc("setcalc", "ЗвичайнаЗарплата", PayDef + "");
            DB.MyUpdateCalc("setcalc", "Стажер_1", st1 + "");
            DB.MyUpdateCalc("setcalc", "Стажер_2", st2 + "");
            DB.finalize();
            getParam();
            }
            catch(Exception ex)
            {
            
            }
        }
        else
        {
        JOptionPane.showMessageDialog(this, "Заповніть всі поля", "Помилка", 2);
        }
    }//GEN-LAST:event_btnSave2ActionPerformed

    private void txtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateActionPerformed

    private void txtPayDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayDefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayDefActionPerformed

    private void txtValueKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValueKHMouseClicked
        
    }//GEN-LAST:event_txtValueKHMouseClicked

    private void txtValueKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueKHKeyTyped
       char c = evt.getKeyChar();
        if ((Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_PERIOD))) {
            
            if( (c == KeyEvent.VK_PERIOD && txtValueKH.getText().indexOf(".")!=-1) || (c == KeyEvent.VK_PERIOD && txtValueKH.getText().length()==0))
            {
                evt.consume();
            }
        }
        else
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtValueKHKeyTyped

    private void txtTakeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTakeKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_PERIOD))) {
            if( (c == KeyEvent.VK_PERIOD && txtValueKH.getText().indexOf(".")!=-1) || (c == KeyEvent.VK_PERIOD && txtValueKH.getText().length()==0))
            {
                evt.consume();
            }
        }
        else
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtTakeKeyTyped

    private void txtPayRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayRateKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_PERIOD))) {
            if( (c == KeyEvent.VK_PERIOD && txtValueKH.getText().indexOf(".")!=-1) || (c == KeyEvent.VK_PERIOD && txtValueKH.getText().length()==0))
            {
                evt.consume();
            }
        }
        else
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtPayRateKeyTyped

    private void txtRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRateKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_PERIOD))) {
            if( (c == KeyEvent.VK_PERIOD && txtValueKH.getText().indexOf(".")!=-1) || (c == KeyEvent.VK_PERIOD && txtValueKH.getText().length()==0))
            {
                evt.consume();
            }
        }
        else
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtRateKeyTyped

    private void txtPayDefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayDefKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_PERIOD))) {
            if( (c == KeyEvent.VK_PERIOD && txtValueKH.getText().indexOf(".")!=-1) || (c == KeyEvent.VK_PERIOD && txtValueKH.getText().length()==0))
            {
                evt.consume();
            }
        }
        else
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtPayDefKeyTyped

    private void txtSt1PayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSt1PayKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_PERIOD))) {
            if( (c == KeyEvent.VK_PERIOD && txtValueKH.getText().indexOf(".")!=-1) || (c == KeyEvent.VK_PERIOD && txtValueKH.getText().length()==0))
            {
                evt.consume();
            }
        }
        else
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtSt1PayKeyTyped

    private void txtSt2PayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSt2PayKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_PERIOD))) {
            if( (c == KeyEvent.VK_PERIOD && txtValueKH.getText().indexOf(".")!=-1) || (c == KeyEvent.VK_PERIOD && txtValueKH.getText().length()==0))
            {
                evt.consume();
            }
        }
        else
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtSt2PayKeyTyped

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        dispose();
        FormMenu.setCountForm(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        
    }//GEN-LAST:event_lblExitMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSettingsCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSettingsCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSettingsCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSettingsCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSettingsCalculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JPanel pnlHead;
    public javax.swing.JTextField txtPayDef;
    public javax.swing.JTextField txtPayRate;
    public javax.swing.JTextField txtRate;
    public javax.swing.JTextField txtSt1Pay;
    public javax.swing.JTextField txtSt2Pay;
    public javax.swing.JTextField txtTake;
    public javax.swing.JTextField txtValueKH;
    // End of variables declaration//GEN-END:variables
}
