/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ximik
 */
public class FormAddPayment extends javax.swing.JFrame {

    /**
     * @return the Type
     */
    public static String getTypewx() {
        return Type;
    }

    /**
     * @param aType the Type to set
     */
    public static void setType(String aType) {
        Type = aType;
    }

    /**
     * @return the id
     */
    public static String getId() {
        return id;
    }

    /**
     * @param aId the id to set
     */
    public static void setId(String aId) {
        id = aId;
    }

    /**
     * @return the Date
     */
    public static String getDate() {
        return Date;
    }

    /**
     * @param aDate the Date to set
     */
    public static void setDate(String aDate) {
        Date = aDate;
    }

    /**
     * @return the Suma
     */
    public static String getSuma() {
        return Suma;
    }

    /**
     * @param aSuma the Suma to set
     */
    public static void setSuma(String aSuma) {
        Suma = aSuma;
    }

    /**
     * @return the nameCashier
     */
    public static String getNameCashier() {
        return nameCashier;
    }

    /**
     * @param aNameCashier the nameCashier to set
     */
    public static void setNameCashier(String aNameCashier) {
        nameCashier = aNameCashier;
    }

   

    /**
     * @return the variantStart
     */
    public static int getVariantStart() {
        return variantStart;
    }

    /**
     * @param aVariantStart the variantStart to set
     */
    public static void setVariantStart(int aVariantStart) {
        variantStart = aVariantStart;
    }

    ResultSet X = null;
    DataBase a = new DataBase();
    static int countPerson = 0;
    public static ArrayList<String> listPerson = new ArrayList<>();
    public static ArrayList<String> listEdit = new ArrayList<>();
    private static int variantStart = 0;
    
    private static int countP = 0;
    
    private static String id = "";
    private static String nameCashier = "";
    private static String Date = "";
    private static String Suma = "";
    private static String Type = "";
    /**
     * Creates new form addDay
     */
    public FormAddPayment() {
        initComponents();
        MoveMouseListener mml = new MoveMouseListener(pnlHead, this);
        pnlHead.addMouseListener(mml);
        pnlHead.addMouseMotionListener(mml);
        this.setLocationRelativeTo(null);
        getEmp();
        //Радагування
        if (variantStart == 1) {
            SimpleDateFormat Fr = new SimpleDateFormat("y-MM-d", Locale.ENGLISH);
            try {
                txtType.setText(Type);
                MyDate.setDate(Fr.parse(Date));
                allW.setText(Suma);
            } catch (ParseException ex) {
                Logger.getLogger(FormAddPayment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Component[] comp = pnlEm.getComponents();
            for (int i = 0; i < comp.length; i++) 
            {
                String text = comp[i].toString();
                    if(text.indexOf(getNameCashier())!=-1)
                    {
                        
                        setNameCashier(getNameCashier());
                        pnlEm.getComponent(i).setBackground(new Color(120,101,84));
                    
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlEm = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblExit1 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        TitleCalendar3 = new javax.swing.JLabel();
        MyDate = new com.toedter.calendar.JDateChooser();
        allW = new javax.swing.JTextField();
        TitleCalendar = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        TitleCalendar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(240, 219, 189));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlEm.setBackground(new java.awt.Color(255, 255, 255));
        pnlEm.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(pnlEm);

        pnlHead.setBackground(new java.awt.Color(70, 43, 25));
        pnlHead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHeadMousePressed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Додавання виплати");

        lblExit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit-2.png"))); // NOI18N
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(lblExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblExit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtType.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTypeKeyTyped(evt);
            }
        });

        TitleCalendar3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TitleCalendar3.setForeground(new java.awt.Color(70, 43, 25));
        TitleCalendar3.setText("Тип виплати:");
        TitleCalendar3.setToolTipText("");

        MyDate.setDateFormatString("y-M-d");

        allW.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        allW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                allWKeyTyped(evt);
            }
        });

        TitleCalendar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TitleCalendar.setForeground(new java.awt.Color(70, 43, 25));
        TitleCalendar.setText("Дата ");

        btnSave.setBackground(new java.awt.Color(120, 101, 84));
        btnSave.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/file-5.png"))); // NOI18N
        btnSave.setText("Зберегти");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        TitleCalendar1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TitleCalendar1.setForeground(new java.awt.Color(70, 43, 25));
        TitleCalendar1.setText("Розмір виплати:");
        TitleCalendar1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TitleCalendar))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(MyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(TitleCalendar3))
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleCalendar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allW, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnSave))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitleCalendar)
                .addGap(1, 1, 1)
                .addComponent(MyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleCalendar3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       //getEmp();
    }//GEN-LAST:event_formWindowOpened

    /**
     * Отримання працівників
     */
    void getEmp()
    {
     a.GetInfoBoxAll("PIB", "employees");
        pnlEm.removeAll();
        for (int i = 0; i < a.list.size(); i++) {
            pnlEm.add(CreateBtn(a.array[i], 0));
        }
        pnlEm.updateUI();
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (getNameCashier() != "" && allW.getText().length() > 0 && MyDate.getDate() != null && txtType.getText().length()>0) {
            String result = listPerson.stream()
                    .map(n -> String.valueOf(n))
                    .collect(Collectors.joining());
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            double allWe = Double.parseDouble(allW.getText());
            double salary = 0;
            if (variantStart == 0) {
                a.MyInsertPayment("Payments", getNameCashier(), dateFormat.format(MyDate.getDate()), txtType.getText(), allWe);
                JOptionPane.showMessageDialog(this, "Успішно", "Додавання", 1);
                FormMain.GetData("Payments");
            } else if (variantStart == 1) {
                a.MyUpdatePayment("Payments", getNameCashier(), dateFormat.format(MyDate.getDate()), txtType.getText(), allWe, getId());
                JOptionPane.showMessageDialog(this, "Успішно", "Редагування", 1);
                FormMain.GetData("Payments");
            }
            listEdit.clear();
            listPerson.clear();
            variantStart = 0;
            FormMain.setAddP(0);
            FormMain.setDateRequest(0);
            FormMain.setRequestVariant(0);
            allW.setText("");
            a.finalize();
            dispose();
        } else if (MyDate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Дату не вибрано", "Помилка", 2);
        } else if (getNameCashier() == "") {
            JOptionPane.showMessageDialog(this, "Не вибрано робочого", "Помилка", 2);
        } else if (txtType.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Не вказано вид виплати", "Помилка", 2);
        }
        else if (allW.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Не вказано суму виплати", "Помилка", 2);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void pnlHeadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHeadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlHeadMousePressed

    private void allWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_allWKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isLetterOrDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_SPACE))) {
            
            if( (c == KeyEvent.VK_PERIOD && allW.getText().indexOf(".")!=-1) || (c == KeyEvent.VK_PERIOD && allW.getText().length()==0))
            {
                evt.consume();
            }
        }
        else
        {
        evt.consume();
        }
    }//GEN-LAST:event_allWKeyTyped

    private void txtTypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTypeKeyTyped
        char c = evt.getKeyChar();
        if ((Character.isLetterOrDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)
                || (c == KeyEvent.VK_SPACE))) {
            
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtTypeKeyTyped

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        listEdit.clear();
        listPerson.clear();
        variantStart = 0;
        FormMain.setAddP(0);
        dispose();
    }//GEN-LAST:event_lblExit1MouseClicked

    public void Act() {
        this.isFocusable();
    }

    /**
     * Створення кнопки
     * @param name Ім'я
     * @param variant Варіант кліку
     * @return 
     */
    JButton CreateBtn(String name, int variant) {
        JButton b = new JButton(name);
        b.setPreferredSize(new Dimension(200, 50));
        b.setBackground(Color.WHITE);
        Font BigFontTR = new Font("TimesRoman", Font.BOLD, 14);
        b.setFont(BigFontTR);
        b.setVisible(true);
        b.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.getButton() == MouseEvent.BUTTON3) {
                    b.setBackground(Color.WHITE);
                    setNameCashier("");
                    Component[] comp = pnlEm.getComponents();
                    for(int i=0; i<comp.length; i++)
                    {
                        pnlEm.getComponent(i).setBackground(Color.WHITE);
                    }

                } else if (e.getButton() == MouseEvent.BUTTON1) {
                    setNameCashier(b.getText());
                    Component[] comp = pnlEm.getComponents();
                    for(int i=0; i<comp.length; i++)
                    {
                        pnlEm.getComponent(i).setBackground(Color.WHITE);
                    }
                    b.setBackground(new Color(120,101,84));
                }
            }
        });

        return b;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAddPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser MyDate;
    private javax.swing.JLabel TitleCalendar;
    private javax.swing.JLabel TitleCalendar1;
    private javax.swing.JLabel TitleCalendar3;
    private javax.swing.JTextField allW;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlEm;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
