/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.sql.Connection;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ximik
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * @return the countForm
     */
    public static int getCountForm() {
        return countForm;
    }

    /**
     * @param aCountForm the countForm to set
     */
    public static void setCountForm(int aCountForm) {
        countForm = aCountForm;
    }

    /**
     * Creates new form FormMenu
     */
    public static int countForm = 0;
    public static Connection conn = null;
    FormMain main = new FormMain();
    FormSettingsConnect st = new FormSettingsConnect();
    private static DataBase a = new DataBase();
    static int statusCon = 0; //Активність кнопок при підключенні
    public FormMenu() {
        initComponents();
        MoveMouseListener mml = new MoveMouseListener(pnlHead, this);
        pnlHead.addMouseListener(mml);
        pnlHead.addMouseMotionListener(mml);
        this.setLocationRelativeTo(null);
        PlugIn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName10 = new javax.swing.JLabel();
        lblName11 = new javax.swing.JLabel();
        pnlAllWork = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pnlCashier = new javax.swing.JPanel();
        lblPhoto1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        pnlinterns = new javax.swing.JPanel();
        lblPhoto2 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        pnlPayments = new javax.swing.JPanel();
        lblPhoto3 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        pnlEmployyes = new javax.swing.JPanel();
        lblPhoto4 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        pnlExit = new javax.swing.JPanel();
        lblPhoto7 = new javax.swing.JLabel();
        lblName7 = new javax.swing.JLabel();
        pnlConnect = new javax.swing.JPanel();
        pnlStatusCon = new javax.swing.JPanel();
        lblPhoto6 = new javax.swing.JLabel();
        lblName6 = new javax.swing.JLabel();
        lblName9 = new javax.swing.JLabel();
        pnlCalc = new javax.swing.JPanel();
        lblPhoto5 = new javax.swing.JLabel();
        lblName5 = new javax.swing.JLabel();
        lblName8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        pnlHead.setBackground(new java.awt.Color(70, 43, 25));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/logo.png"))); // NOI18N

        lblName10.setBackground(new java.awt.Color(0, 0, 0));
        lblName10.setFont(new java.awt.Font("Times New Roman", 3, 40)); // NOI18N
        lblName10.setForeground(new java.awt.Color(255, 255, 255));
        lblName10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName10.setText("Магазин напівфабрикатів \"Галя Балувана\"");

        lblName11.setBackground(new java.awt.Color(0, 0, 0));
        lblName11.setFont(new java.awt.Font("Times New Roman", 3, 40)); // NOI18N
        lblName11.setForeground(new java.awt.Color(255, 255, 255));
        lblName11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName11.setText("Готують тут виключно\nпо-домашньому та з любов'ю");

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeadLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName11, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblName10, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAllWork.setBackground(new java.awt.Color(240, 219, 189));
        pnlAllWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAllWorkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAllWorkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAllWorkMouseExited(evt);
            }
        });

        lblPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/process.png"))); // NOI18N

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Виробництво");

        javax.swing.GroupLayout pnlAllWorkLayout = new javax.swing.GroupLayout(pnlAllWork);
        pnlAllWork.setLayout(pnlAllWorkLayout);
        pnlAllWorkLayout.setHorizontalGroup(
            pnlAllWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
            .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAllWorkLayout.setVerticalGroup(
            pnlAllWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllWorkLayout.createSequentialGroup()
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pnlCashier.setBackground(new java.awt.Color(240, 219, 189));
        pnlCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCashierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCashierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCashierMouseExited(evt);
            }
        });

        lblPhoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/cash-register.png"))); // NOI18N

        lblName1.setBackground(new java.awt.Color(0, 0, 0));
        lblName1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblName1.setForeground(new java.awt.Color(0, 0, 0));
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName1.setText("Каса");

        javax.swing.GroupLayout pnlCashierLayout = new javax.swing.GroupLayout(pnlCashier);
        pnlCashier.setLayout(pnlCashierLayout);
        pnlCashierLayout.setHorizontalGroup(
            pnlCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPhoto1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        pnlCashierLayout.setVerticalGroup(
            pnlCashierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCashierLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblPhoto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlinterns.setBackground(new java.awt.Color(240, 219, 189));
        pnlinterns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlinternsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlinternsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlinternsMouseExited(evt);
            }
        });

        lblPhoto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/name.png"))); // NOI18N

        lblName2.setBackground(new java.awt.Color(0, 0, 0));
        lblName2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblName2.setForeground(new java.awt.Color(0, 0, 0));
        lblName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName2.setText("Стажери");

        javax.swing.GroupLayout pnlinternsLayout = new javax.swing.GroupLayout(pnlinterns);
        pnlinterns.setLayout(pnlinternsLayout);
        pnlinternsLayout.setHorizontalGroup(
            pnlinternsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPhoto2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        pnlinternsLayout.setVerticalGroup(
            pnlinternsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinternsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlPayments.setBackground(new java.awt.Color(240, 219, 189));
        pnlPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPaymentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPaymentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPaymentsMouseExited(evt);
            }
        });

        lblPhoto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/cash-payment.png"))); // NOI18N

        lblName3.setBackground(new java.awt.Color(0, 0, 0));
        lblName3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblName3.setForeground(new java.awt.Color(0, 0, 0));
        lblName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName3.setText("Виплати");

        javax.swing.GroupLayout pnlPaymentsLayout = new javax.swing.GroupLayout(pnlPayments);
        pnlPayments.setLayout(pnlPaymentsLayout);
        pnlPaymentsLayout.setHorizontalGroup(
            pnlPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPhoto3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        pnlPaymentsLayout.setVerticalGroup(
            pnlPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlEmployyes.setBackground(new java.awt.Color(240, 219, 189));
        pnlEmployyes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEmployyesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlEmployyesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlEmployyesMouseExited(evt);
            }
        });

        lblPhoto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/employee.png"))); // NOI18N

        lblName4.setBackground(new java.awt.Color(0, 0, 0));
        lblName4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblName4.setForeground(new java.awt.Color(0, 0, 0));
        lblName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName4.setText("Працівники");

        javax.swing.GroupLayout pnlEmployyesLayout = new javax.swing.GroupLayout(pnlEmployyes);
        pnlEmployyes.setLayout(pnlEmployyesLayout);
        pnlEmployyesLayout.setHorizontalGroup(
            pnlEmployyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPhoto4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        pnlEmployyesLayout.setVerticalGroup(
            pnlEmployyesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployyesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlExit.setBackground(new java.awt.Color(240, 219, 189));
        pnlExit.setPreferredSize(new java.awt.Dimension(159, 173));
        pnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExitMouseExited(evt);
            }
        });

        lblPhoto7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/exit-door.png"))); // NOI18N

        lblName7.setBackground(new java.awt.Color(0, 0, 0));
        lblName7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblName7.setForeground(new java.awt.Color(0, 0, 0));
        lblName7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName7.setText("Вихід");

        javax.swing.GroupLayout pnlExitLayout = new javax.swing.GroupLayout(pnlExit);
        pnlExit.setLayout(pnlExitLayout);
        pnlExitLayout.setHorizontalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPhoto7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        pnlExitLayout.setVerticalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPhoto7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName7)
                .addContainerGap())
        );

        pnlConnect.setBackground(new java.awt.Color(240, 219, 189));
        pnlConnect.setPreferredSize(new java.awt.Dimension(159, 173));
        pnlConnect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlConnectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlConnectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlConnectMouseExited(evt);
            }
        });
        pnlConnect.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlStatusConLayout = new javax.swing.GroupLayout(pnlStatusCon);
        pnlStatusCon.setLayout(pnlStatusConLayout);
        pnlStatusConLayout.setHorizontalGroup(
            pnlStatusConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        pnlStatusConLayout.setVerticalGroup(
            pnlStatusConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        pnlConnect.add(pnlStatusCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 113, 18, 14));

        lblPhoto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/cloud-database.png"))); // NOI18N
        pnlConnect.add(lblPhoto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 159, -1));

        lblName6.setBackground(new java.awt.Color(0, 0, 0));
        lblName6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblName6.setForeground(new java.awt.Color(0, 0, 0));
        lblName6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName6.setText("Підключення");
        pnlConnect.add(lblName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 159, -1));

        lblName9.setBackground(new java.awt.Color(0, 0, 0));
        lblName9.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        lblName9.setForeground(new java.awt.Color(0, 0, 0));
        lblName9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName9.setText("Налаштування");
        pnlConnect.add(lblName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 159, -1));

        pnlCalc.setBackground(new java.awt.Color(240, 219, 189));
        pnlCalc.setPreferredSize(new java.awt.Dimension(159, 173));
        pnlCalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCalcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCalcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCalcMouseExited(evt);
            }
        });

        lblPhoto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhoto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/analysis.png"))); // NOI18N

        lblName5.setBackground(new java.awt.Color(0, 0, 0));
        lblName5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblName5.setForeground(new java.awt.Color(0, 0, 0));
        lblName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName5.setText("Розрахунків");

        lblName8.setBackground(new java.awt.Color(0, 0, 0));
        lblName8.setFont(new java.awt.Font("Times New Roman", 3, 22)); // NOI18N
        lblName8.setForeground(new java.awt.Color(0, 0, 0));
        lblName8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName8.setText("Налаштування");

        javax.swing.GroupLayout pnlCalcLayout = new javax.swing.GroupLayout(pnlCalc);
        pnlCalc.setLayout(pnlCalcLayout);
        pnlCalcLayout.setHorizontalGroup(
            pnlCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPhoto5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
            .addComponent(lblName8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCalcLayout.setVerticalGroup(
            pnlCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalcLayout.createSequentialGroup()
                .addComponent(lblName8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPhoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName5)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(pnlAllWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCashier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlinterns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(pnlPayments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(pnlEmployyes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlAllWork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlinterns, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEmployyes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlExit, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(pnlConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCalc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAllWorkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAllWorkMouseEntered
        if(statusCon==0)
        {
        pnlAllWork.setBackground(new Color(70, 43, 25));
        lblName.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_pnlAllWorkMouseEntered

    private void pnlAllWorkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAllWorkMouseExited
        if(statusCon==0)
        {
        pnlAllWork.setBackground(new Color(240, 219, 189));
        lblName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pnlAllWorkMouseExited

    private void pnlCashierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCashierMouseEntered
        if(statusCon==0)
        {
        pnlCashier.setBackground(new Color(70, 43, 25));
        lblName1.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_pnlCashierMouseEntered

    private void pnlCashierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCashierMouseExited
        if(statusCon==0)
        {
        pnlCashier.setBackground(new Color(240, 219, 189));
        lblName1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pnlCashierMouseExited

    private void pnlinternsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlinternsMouseEntered
        if(statusCon==0)
        {
        pnlinterns.setBackground(new Color(70, 43, 25));
        lblName2.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_pnlinternsMouseEntered

    private void pnlinternsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlinternsMouseExited
        if(statusCon==0)
        {
        pnlinterns.setBackground(new Color(240, 219, 189));
        lblName2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pnlinternsMouseExited

    private void pnlPaymentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPaymentsMouseEntered
        if(statusCon==0)
        {
        pnlPayments.setBackground(new Color(70, 43, 25));
        lblName3.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_pnlPaymentsMouseEntered

    private void pnlPaymentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPaymentsMouseExited
        if(statusCon==0)
        {
        pnlPayments.setBackground(new Color(240, 219, 189));
        lblName3.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pnlPaymentsMouseExited

    private void pnlEmployyesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEmployyesMouseEntered
        if(statusCon==0)
        {
        pnlEmployyes.setBackground(new Color(70, 43, 25));
        lblName4.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_pnlEmployyesMouseEntered

    private void pnlEmployyesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEmployyesMouseExited
        if(statusCon==0)
        {
        pnlEmployyes.setBackground(new Color(240, 219, 189));
        lblName4.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pnlEmployyesMouseExited

    private void pnlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseEntered
        pnlExit.setBackground(new Color(70, 43, 25));
        lblName7.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlExitMouseEntered

    private void pnlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseExited
        pnlExit.setBackground(new Color(240, 219, 189));
        lblName7.setForeground(Color.BLACK);
    }//GEN-LAST:event_pnlExitMouseExited

    private void pnlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_pnlExitMouseClicked

    private void pnlConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlConnectMouseClicked
        if (getCountForm() == 0) {
            FormSettingsConnect StC = new FormSettingsConnect();
            StC.setVisible(true);
            setCountForm(1);
        }
    }//GEN-LAST:event_pnlConnectMouseClicked

    private void pnlConnectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlConnectMouseEntered
        pnlConnect.setBackground(new Color(70, 43, 25));
        lblName6.setForeground(Color.WHITE);
        lblName9.setForeground(Color.WHITE);
    }//GEN-LAST:event_pnlConnectMouseEntered

    private void pnlConnectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlConnectMouseExited
        pnlConnect.setBackground(new Color(240, 219, 189));
        lblName6.setForeground(Color.BLACK);
        lblName9.setForeground(Color.BLACK);
    }//GEN-LAST:event_pnlConnectMouseExited

    private void pnlCalcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCalcMouseClicked
        if (getCountForm() == 0 && statusCon==0) {
            FormSettingsCalculation St = new FormSettingsCalculation();
            St.setVisible(true);
            setCountForm(1);
        }
    }//GEN-LAST:event_pnlCalcMouseClicked

    private void pnlCalcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCalcMouseEntered
        if(statusCon==0)
        {
        pnlCalc.setBackground(new Color(70, 43, 25));
        lblName5.setForeground(Color.WHITE);
        lblName8.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_pnlCalcMouseEntered

    private void pnlCalcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCalcMouseExited
       if(statusCon==0)
        {
        pnlCalc.setBackground(new Color(240, 219, 189));
        lblName5.setForeground(Color.BLACK);
        lblName8.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pnlCalcMouseExited

    private void pnlAllWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAllWorkMouseClicked
        if (getCountForm() == 0 && statusCon==0) {
            FormMain.setNameTbl("allWork");
            FormMain.GetData("allWork");
            main.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_pnlAllWorkMouseClicked

    private void pnlCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCashierMouseClicked
        if (getCountForm() == 0 && statusCon==0) {
            FormMain.setNameTbl("cashier");
            FormMain.GetData("cashier");
            main.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_pnlCashierMouseClicked

    private void pnlinternsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlinternsMouseClicked
        if (getCountForm() == 0 && statusCon==0) {
            FormMain.setNameTbl("Interns");
            FormMain.GetData("Interns");
            main.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_pnlinternsMouseClicked

    private void pnlPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPaymentsMouseClicked
        if (getCountForm() == 0 && statusCon==0) {
            FormMain.setNameTbl("Payments");
            FormMain.GetData("Payments");
            main.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_pnlPaymentsMouseClicked

    private void pnlEmployyesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEmployyesMouseClicked
        if (getCountForm() == 0 && statusCon==0) {
            FormMain.setNameTbl("employees");
            FormMain.GetData("employees");
            main.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_pnlEmployyesMouseClicked

    /**
     * Підключення
     */
    static void PlugIn() {
        FormSettingsConnect o = new FormSettingsConnect();
        FormMenu.conn = null;
        if (FormMenu.conn == null) {
            a.finalize();
            a = null;
            a = new DataBase();
            FormMenu.conn = a.Connect();
            MyThread t = new MyThread();
            if (conn == null) {
                statusCon=1;
                pnlStatusCon.setBackground(new Color(178, 34, 34));
                t.start();
            } else {
                pnlAllWork.setBackground(new Color(240, 219, 189));
                pnlCashier.setBackground(new Color(240, 219, 189));
                pnlCalc.setBackground(new Color(240, 219, 189));
                pnlEmployyes.setBackground(new Color(240, 219, 189));
                pnlPayments.setBackground(new Color(240, 219, 189));
                pnlinterns.setBackground(new Color(240, 219, 189));
                pnlStatusCon.setBackground(new Color(0, 255, 0));
                statusCon=0;
                t.interrupt();
            }
        }
    }

    public static class MyThread extends Thread {

        public void run() {
            long sum = 0;
            while (conn == null) {
                try {
                    pnlAllWork.setBackground(new Color(178, 34, 34));
                    pnlCashier.setBackground(new Color(178, 34, 34));
                    pnlCalc.setBackground(new Color(178, 34, 34));
                    pnlEmployyes.setBackground(new Color(178, 34, 34));
                    pnlPayments.setBackground(new Color(178, 34, 34));
                    pnlinterns.setBackground(new Color(178, 34, 34));
                    Thread.sleep(TimeUnit.SECONDS.toMillis(1));
                    pnlAllWork.setBackground(new Color(240, 219, 189));
                    pnlCashier.setBackground(new Color(240, 219, 189));
                    pnlCalc.setBackground(new Color(240, 219, 189));
                    pnlEmployyes.setBackground(new Color(240, 219, 189));
                    pnlPayments.setBackground(new Color(240, 219, 189));
                    pnlinterns.setBackground(new Color(240, 219, 189));
                    Thread.sleep(TimeUnit.SECONDS.toMillis(1));
                } catch (InterruptedException ex) {
                    Logger.getLogger(FormMenu.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName10;
    private javax.swing.JLabel lblName11;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JLabel lblName9;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhoto1;
    private javax.swing.JLabel lblPhoto2;
    private javax.swing.JLabel lblPhoto3;
    private javax.swing.JLabel lblPhoto4;
    private javax.swing.JLabel lblPhoto5;
    private javax.swing.JLabel lblPhoto6;
    private javax.swing.JLabel lblPhoto7;
    public static javax.swing.JPanel pnlAllWork;
    public static javax.swing.JPanel pnlCalc;
    public static javax.swing.JPanel pnlCashier;
    public static javax.swing.JPanel pnlConnect;
    public static javax.swing.JPanel pnlEmployyes;
    public static javax.swing.JPanel pnlExit;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlMain;
    public static javax.swing.JPanel pnlPayments;
    public static javax.swing.JPanel pnlStatusCon;
    public static javax.swing.JPanel pnlinterns;
    // End of variables declaration//GEN-END:variables
}
